### PR TITLE
Feature/travis support

### PR DESCRIPTION
**Pull request by eddelbuettel**
This adds Travis support.  And it even upgrades to g++-4.9.  

Sadly, though, it still fails -- but this may now be something for you to look at.  On my box, `configure && make && make check` works fine.

You will have to 'link' Travis and GitHub, see eg [the first few paragraphs here](http://docs.travis-ci.com/user/getting-started/).  The pull request gets you working `.travis.yml` so on new commits it will run the tests for you.   

I also added two simple helpers `bootstrap.sh` (to call the auto\* helpers) and `cleanup.sh` to remove their artifacts.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Ok, now both the g++ and clang++ branches build, but neither invokes the test.

**Comment by dcdillon** [comment]
Not in particular.  That's just how I learned it from the autotools tutorials I found.  And I have an inkling why make check is failing, but I'll have to do some research.  I'm going to merge it as-is then make a few changes (i think the cleanup is not quite complete)

**Comment by eddelbuettel** [comment]
Sounds good.  My main point with the PR was to 
- set up Travis for a pure C++ project which I hadn't done before (but we do it for all R packages)
- show you how useful Travis can be across a matrix of compilers (eg the PPA I point to has g++ 5 ready for use)

**Comment by dcdillon** [comment]
Yeah.  Thats pretty cool.  And it actually exposes a flaw in my code.  I've only tested on Centos 6 and Ubuntu 14.10.  Whatever version Travis is using has a different sysfs layout than I have encountered yet.

**Comment by eddelbuettel** [comment]
And it gives us a working playground for `catch.h` as well which does indeed look good.  I really dislike ALLUPPERCASE notation though :-/

I guess you did notice or catch that with clang++ the `make check` part actually ends in a segfault?

**Comment by dcdillon** [comment]
Yeah.  The all uppercase stuff is because they are macros and traditionally that's how macros are done so they aren't confused with functions.

I didn't see that it segfaulted, but I can imagine why.  Going to start playing with docker a bit to see if i can't handle more sysfs layouts.

**Comment by dcdillon** [comment]
Fixed all the stuff for make check.  And you made the front page of http://dcdillon.github.io/cpuaff.  It raised a couple of issues and I had to really fight with it to make the tests pass with travis, but everything looks good now.  I also was able to fix a couple small bugs and some compiler warnings because of the travis integration.  Thanks!

**Comment by eddelbuettel** [comment]
Woot!

**Pull request merged**
